spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-cache?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: a1301493116
    driver-class-name: com.mysql.cj.jdbc.Driver

#开启驼峰命名匹配规则
mybatis:
  configuration:
    map-underscore-to-camel-case: true
