server:
  port: 8090
spring:
  profiles:
    active: dev
---

server:
  port: 8091
spring:
  profiles: dev
---
server:
  port: 8092
spring:
  profiles: prod

#person:
#  name: ev
#  age: 22
#  boss: false
#  birth: 2017/12/12
#  maps: {k1: v1,k2: v2}
#  lists:
#    - wei
#    - yi
#    - zhao
#  dog:
#    name: 小狗
#    age: 2

